name: Docker Build, Tag and Push
run-name: builds docker image, tag it and push to dockerhub
on:
  push:
    branches:
      - master
jobs:
  build-tag-push:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo to VM
        uses: actions/checkout@v4
      - name: Build the docker image
        run: docker build . --file Dockerfile.dev --tag monyetype:latest
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: Tag the docker image
        run: docker tag monyetype:latest arimotearipo/monyetype:latest
      - name: Push the tagged docker image to repository
        run: docker push arimotearipo/monyetype:latest
