name: Build Nextjs
run-name: builds the Nextjs application
on:
  push:
    branches:
      - feature/*
      - fix/*
  workflow_dispatch:

jobs:
  build-nextjs:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo to VM
        uses: actions/checkout@v4
      - name: Install packages
        run: npm install
      - name: Run postgres container
        run: docker compose up -d postgres
      - name: Build Nextjs
        run: npm run build
      - name: Stop containers
        run: docker compose down
